name: "Build and upload docker image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_TAG: 15-server:0.3

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${IMAGE_TAG}"

    - name: Save Docker image
      run: docker save --output image.tar "${IMAGE_TAG}"

    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: image.tar
        retention-days: 1