name: "Build and upload docker image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_TAG: 15-server:0.3

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set outputs
      id: commit_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Check outputs
      run: echo ${{ steps.commit_sha.outputs.sha_short }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${{ steps.commit_sha.outputs.sha_short }}"

    - name: Save Docker image
      run: docker save --output image.tar "${{ steps.commit_sha.outputs.sha_short }}"

    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: image.tar
        retention-days: 1